import type { Variants } from "framer-motion";
const ease: [number, number, number, number] = [0.22, 1, 0.36, 1];
export const viewport = { once: true, amount: 0.2 } as const;
export const fadeUp: Variants = { hidden: { opacity: 0, y: 40 }, show: { opacity: 1, y: 0, transition: { duration: 0.8, ease } } };
export const fadeIn: Variants = { hidden: { opacity: 0 }, show: { opacity: 1, transition: { duration: 0.8 } } };
export const slideLeft: Variants = { hidden: { opacity: 0, x: -60 }, show: { opacity: 1, x: 0, transition: { duration: 0.9, ease } } };
export const slideRight: Variants = { hidden: { opacity: 0, x: 60 }, show: { opacity: 1, x: 0, transition: { duration: 0.9, ease } } };
export const scaleIn: Variants = { hidden: { opacity: 0, scale: 0.94 }, show: { opacity: 1, scale: 1, transition: { duration: 0.8, ease } } };
export const imageReveal: Variants = { hidden: { clipPath: "inset(100% 0 0 0)" }, show: { clipPath: "inset(0% 0 0 0)", transition: { duration: 1.2, ease } } };
export const staggerContainer: Variants = { hidden: {}, show: { transition: { staggerChildren: 0.12 } } };
